# Generated by Django 2.2.5 on 2019-10-31 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191010_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='graph',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
